**welcome to numpy tutorial**

In [115]:
import numpy as np 

In [116]:
ar = np.array(5)
ar

array(5)

In [117]:
ar.ndim

0

In [118]:
ar1 = np.array([5,6])  #1D array(vector)
ar1

array([5, 6])

In [119]:
ar1.ndim

1

In [120]:
ar2 = np.array([[1,2,3],[2,3,4]])  ##2D array(matrix)
ar2

array([[1, 2, 3],
       [2, 3, 4]])

In [121]:
ar3 = np.array([[[1,2],[2,3],[3,4]]])   ### 3D array(3D tensor)
ar3

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [122]:
ar3.ndim

3

In [123]:
ar3.shape

(1, 3, 2)

In [124]:
ar3.size

6

In [125]:
# arange function
ar4 = np.arange(1,10)
ar4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
ar4 = np.arange(1,10,2)
ar4

array([1, 3, 5, 7, 9])

In [127]:
np.array([1,2,3,4],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [128]:
np.array([1,2,3,4],dtype = float)

array([1., 2., 3., 4.])

In [129]:
#reshape function 
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [130]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [131]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [132]:
#np.random
np.random.random((3,4))

array([[0.42890009, 0.13079983, 0.44355345, 0.87394628],
       [0.1221641 , 0.96102885, 0.7374496 , 0.51558355],
       [0.23541495, 0.64733468, 0.75092085, 0.8711166 ]])

In [133]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [134]:
#np.identity
np.identity(45)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [135]:
np.identity(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Array Atributes

In [136]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [137]:
#ndim
a1.ndim

1

In [138]:
a2.ndim

2

In [139]:
a3.ndim

3

In [140]:
#shape
a1.shape


(10,)

In [141]:
a2.shape

(3, 4)

In [142]:
a3.shape


(2, 2, 2)

In [143]:
#size
a3.size

8

In [144]:
a2.size

12

In [145]:
a1.size

10

In [146]:
#itemsize
a3.itemsize

8

In [147]:
a2.itemsize

8

In [148]:
#dtype
a1.dtype

dtype('int64')

In [149]:
a2.dtype


dtype('float64')

In [150]:
a3.dtype


dtype('int64')

Changing Datatype

In [151]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array Operation

In [152]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [153]:
#scalar operations
#arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [154]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [155]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [156]:
#relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [158]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [159]:
#vector operations
#arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [160]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [161]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [162]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 3., 82., 35.],
       [28., 99., 73.],
       [ 5.,  1., 31.]])

In [163]:
#max
np.max(a1)

np.float64(99.0)

In [164]:
#min
np.min(a1)

np.float64(1.0)

In [165]:
#sum
np.sum(a1)

np.float64(357.0)

In [166]:
#product function
np.prod(a1)

np.float64(270054199800.0)

In [167]:
#row/column wise also
# 0 -> col and 1 -> row
np.max(a1,axis = 0 )

array([28., 99., 73.])

In [168]:
np.min(a1,axis = 1)

array([ 3., 28.,  1.])

In [169]:
#mean
np.mean(a1)

np.float64(39.666666666666664)

In [170]:
np.median(a1)

np.float64(31.0)

In [171]:
#trignometric function
np.sin(a1)

array([[ 0.14112001,  0.31322878, -0.42818267],
       [ 0.27090579, -0.99920683, -0.67677196],
       [-0.95892427,  0.84147098, -0.40403765]])

In [172]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [173]:
#log and exponents
np.exp(a1)

array([[2.00855369e+01, 4.09399696e+35, 1.58601345e+15],
       [1.44625706e+12, 9.88903032e+42, 5.05239363e+31],
       [1.48413159e+02, 2.71828183e+00, 2.90488497e+13]])

In [174]:
np.log(a1)

array([[1.09861229, 4.40671925, 3.55534806],
       [3.33220451, 4.59511985, 4.29045944],
       [1.60943791, 0.        , 3.4339872 ]])

In [175]:
#round/floor/ceil
np.random.random((2,3))

array([[0.92069753, 0.26957702, 0.89454844],
       [0.83238155, 0.5843314 , 0.20967991]])

In [176]:
np.round(np.random.random((2,3))*100)

array([[94., 79., 17.],
       [98.,  7., 81.]])

In [177]:
np.floor(np.random.random((2,3))*100)

array([[45., 78., 20.],
       [13., 81., 61.]])

In [178]:
np.ceil(np.random.random((2,3))*100)

array([[33., 80., 80.],
       [15., 31., 82.]])

Indexing and Slicing

In [179]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a1[-1]

np.int64(9)

In [182]:
a1[4]

np.int64(4)

In [183]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
a2[1,2]

np.int64(6)

In [185]:
a2[1,0]

np.int64(4)

In [186]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [187]:
a3[1,0,1]

np.int64(5)

In [188]:
a3[0,1,0]

np.int64(2)

In [189]:
a3[0,0,0]

np.int64(0)

In [190]:
a3[1,1,0]

np.int64(6)

#slicing

In [191]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
a1[2:5]

array([2, 3, 4])

In [193]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
a2[0,:]

array([0, 1, 2, 3])

In [195]:
a2[:,2]

array([ 2,  6, 10])

In [196]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [197]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [198]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [199]:
a2[1,::3]

array([4, 7])

In [200]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [201]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [202]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [203]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [204]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [205]:
a3[0,1,:]

array([3, 4, 5])

In [206]:
a3[1,:,1]

array([10, 13, 16])

In [207]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [208]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [209]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [210]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [211]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [212]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


***Reshaping***

In [213]:
#tranpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [214]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [215]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

****stacking****

In [216]:
#horizontal stacking

In [217]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [218]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [219]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [220]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

*****Splitting*********

In [221]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [223]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [224]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [225]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]