In [76]:
import numpy as np

# Np.sort

In [77]:
a = np.random.randint(1,100,15)
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [78]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[92, 83,  7,  7],
       [39, 66, 92, 21],
       [44,  1, 40, 96],
       [99, 21, 20, 92],
       [96, 50, 25, 11],
       [82, 17, 11, 67]], dtype=int32)

In [79]:
np.sort(a)

array([19, 39, 51, 64, 68, 69, 70, 71, 72, 72, 83, 85, 88, 91, 92],
      dtype=int32)

In [80]:
np.sort(a)[::-1]

array([92, 91, 88, 85, 83, 72, 72, 71, 70, 69, 68, 64, 51, 39, 19],
      dtype=int32)

In [81]:
np.sort(b,axis= 0)

array([[39,  1,  7,  7],
       [44, 17, 11, 11],
       [82, 21, 20, 21],
       [92, 50, 25, 67],
       [96, 66, 40, 92],
       [99, 83, 92, 96]], dtype=int32)

# np.append

In [82]:
np.append(a,200)

array([ 71,  68,  72,  19,  51,  91,  39,  83,  69,  85,  70,  88,  72,
        64,  92, 200])

In [83]:
b

array([[92, 83,  7,  7],
       [39, 66, 92, 21],
       [44,  1, 40, 96],
       [99, 21, 20, 92],
       [96, 50, 25, 11],
       [82, 17, 11, 67]], dtype=int32)

In [84]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [85]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[92., 83.,  7.,  7.,  1.],
       [39., 66., 92., 21.,  1.],
       [44.,  1., 40., 96.,  1.],
       [99., 21., 20., 92.,  1.],
       [96., 50., 25., 11.,  1.],
       [82., 17., 11., 67.,  1.]])

# np.concatinate

In [86]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [87]:
np.concatenate((c,d),axis = 0 )

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [88]:
np.concatenate((c,d),axis = 1 )

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [89]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

In [90]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [91]:
np.expand_dims(a,axis=0)

array([[71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92]],
      dtype=int32)

# np.where

In [92]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [93]:
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [94]:
np.where(a>50,0,a)

array([ 0,  0,  0, 19,  0,  0, 39,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

# np.argmax

In [95]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [96]:
np.argmax(a)

np.int64(14)

In [97]:
b

array([[92, 83,  7,  7],
       [39, 66, 92, 21],
       [44,  1, 40, 96],
       [99, 21, 20, 92],
       [96, 50, 25, 11],
       [82, 17, 11, 67]], dtype=int32)

In [98]:
np.argmax(b,axis=1)

array([0, 2, 3, 0, 0, 0])

In [99]:
np.argmax(b,axis=0)

array([3, 0, 1, 2])

In [100]:
np.argmin(a)

np.int64(3)

# np.cumsum

In [101]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [102]:
np.cumsum(a)

array([  71,  139,  211,  230,  281,  372,  411,  494,  563,  648,  718,
        806,  878,  942, 1034])

In [103]:
b

array([[92, 83,  7,  7],
       [39, 66, 92, 21],
       [44,  1, 40, 96],
       [99, 21, 20, 92],
       [96, 50, 25, 11],
       [82, 17, 11, 67]], dtype=int32)

In [104]:
np.cumsum(b)

array([  92,  175,  182,  189,  228,  294,  386,  407,  451,  452,  492,
        588,  687,  708,  728,  820,  916,  966,  991, 1002, 1084, 1101,
       1112, 1179])

In [105]:
np.cumsum(b,axis = 0)

array([[ 92,  83,   7,   7],
       [131, 149,  99,  28],
       [175, 150, 139, 124],
       [274, 171, 159, 216],
       [370, 221, 184, 227],
       [452, 238, 195, 294]])

In [106]:
#np.cumprod
np.cumprod(a)

array([                  71,                 4828,               347616,
                    6604704,            336839904,          30652431264,
              1195444819296,       99221920001568,     6846312480108192,
         581936560809196320,  3842071109224639168,  6060864284996317696,
       -6339629249294364672,    92097666770796544,  8472985342913282048])

# np.percecntile

In [107]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [108]:
np.percentile(a,100)

np.float64(92.0)

In [109]:
np.percentile(a,0)

np.float64(19.0)

In [110]:
np.percentile(a,58)

np.float64(72.0)

# np.histogram

In [111]:
a

array([71, 68, 72, 19, 51, 91, 39, 83, 69, 85, 70, 88, 72, 64, 92],
      dtype=int32)

In [112]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 0, 1, 0, 1, 3, 4, 3, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

In [113]:
salary = np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

In [114]:
a = np.array([23,45,6,43,50,60,32,23,90,100])

In [115]:
items=[10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([ 50,  60,  90, 100])

# np.flip

In [116]:
a

array([ 23,  45,   6,  43,  50,  60,  32,  23,  90, 100])

In [117]:
np.flip(a)

array([100,  90,  23,  32,  60,  50,  43,   6,  45,  23])

In [118]:
b

array([[92, 83,  7,  7],
       [39, 66, 92, 21],
       [44,  1, 40, 96],
       [99, 21, 20, 92],
       [96, 50, 25, 11],
       [82, 17, 11, 67]], dtype=int32)

In [119]:
np.flip(b)

array([[67, 11, 17, 82],
       [11, 25, 50, 96],
       [92, 20, 21, 99],
       [96, 40,  1, 44],
       [21, 92, 66, 39],
       [ 7,  7, 83, 92]], dtype=int32)

In [120]:
np.flip(b,axis = 0)

array([[82, 17, 11, 67],
       [96, 50, 25, 11],
       [99, 21, 20, 92],
       [44,  1, 40, 96],
       [39, 66, 92, 21],
       [92, 83,  7,  7]], dtype=int32)

# np.put

In [121]:
a

array([ 23,  45,   6,  43,  50,  60,  32,  23,  90, 100])

In [122]:
np.put(a,[0,1],[10,200])

In [123]:
a

array([ 10, 200,   6,  43,  50,  60,  32,  23,  90, 100])

# np.delete

In [124]:
np.delete(a,[0,2,4])

array([200,  43,  60,  32,  23,  90, 100])

In [125]:
np.delete(a,[0,2,4])

array([200,  43,  60,  32,  23,  90, 100])

# set functions

In [126]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [127]:
np.intersect1d(m,n)

array([3, 4, 5])

In [128]:
np.setdiff1d(m,n)

array([1, 2])

In [129]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [134]:
np.isin(m,2)

array([False,  True, False, False, False])

In [135]:
m[np.isin(m,1)]

array([1])

# np.clip

In [132]:
a

array([ 10, 200,   6,  43,  50,  60,  32,  23,  90, 100])

In [133]:
np.clip(a,a_min=25,a_max=75)

array([25, 75, 25, 43, 50, 60, 32, 25, 75, 75])